/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { EntityListRelationFilter } from "./EntityListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumEntityEntityStatus } from "./EnumEntityEntityStatus";
import { EnumEntityEntityType } from "./EnumEntityEntityType";
import { StringFilter } from "../../util/StringFilter";
import { EntityWhereUniqueInput } from "./EntityWhereUniqueInput";

@InputType()
class EntityWhereInput {
  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  accountOwner?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => EntityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EntityListRelationFilter)
  @IsOptional()
  @Field(() => EntityListRelationFilter, {
    nullable: true,
  })
  childEntities?: EntityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  entityAccountContact?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  entityAccountsPayableEmail?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  entityBillingContact?: UserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  entityName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumEntityEntityStatus,
  })
  @IsEnum(EnumEntityEntityStatus)
  @IsOptional()
  @Field(() => EnumEntityEntityStatus, {
    nullable: true,
  })
  entityStatus?: "Active" | "Suspended" | "Disabled" | "Lead";

  @ApiProperty({
    required: false,
    enum: EnumEntityEntityType,
  })
  @IsEnum(EnumEntityEntityType)
  @IsOptional()
  @Field(() => EnumEntityEntityType, {
    nullable: true,
  })
  entityType?:
    | "GeopathVendor"
    | "GeopathPartner"
    | "MemberMediaOperator"
    | "MemberAgency"
    | "GeopathInternal";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  entityWebsite?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => EntityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => EntityWhereUniqueInput)
  @IsOptional()
  @Field(() => EntityWhereUniqueInput, {
    nullable: true,
  })
  parentEntity?: EntityWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  remoteAccountingId?: StringNullableFilter;
}

export { EntityWhereInput as EntityWhereInput };
