/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EntityCreateNestedManyWithoutUsersInput } from "./EntityCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsBoolean,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => EntityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EntityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EntityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  accountManager?: EntityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => EntityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EntityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EntityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  entityAccountContact?: EntityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => EntityCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => EntityCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => EntityCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  entityBillingContact?: EntityCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isBoardMember?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isFuturesCouncilMember?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  marketingAllowed?: boolean | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  mobileNumber?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  phoneNumber?: number | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  platformReleaseNotificationsAllowed?: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  platformStatusNotificationsAllowed?: boolean | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
